Python_web/modul10/hometask/mysite/app_my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "app_my_site"

urlpatterns = [
    path("", views.main, name="root"),
    path("upload_author", views.upload_author, name="upload_author"),
    path("upload_quote", views.upload_quote, name="upload_quote"),
    path("author/<int:pk>", views.authors_descr, name="authors_descr"),
]

Python_web/modul10/hometask/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app_my_site.urls")),
    path("users/", include("users.urls"))
]

Python_web/modul10/hometask/mysite/users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name='register'),
    path("signin/", LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

Python_web/modul10/hometask/mysite/app_my_site/models.py
from django.db import models
# from django.contrib.auth.models import User
# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=250, null=False)
    born_date = models.DateField(null=False)
    born_location = models.CharField(max_length=250, null=False)
    description = models.TextField(null=False)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    def __str__(self):
        return self.name


class Quote(models.Model):
    tags = models.ManyToManyField(Tag, related_name="quotes")
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name="quotes")
    quote = models.TextField(null=False)
    # user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)

    def __str__(self):
        return f"{self.author.fullname}: '{self.quote[:30]}...'"

Python_web/modul10/hometask/mysite/app_my_site/forms.py
import datetime

from django.forms import ModelForm, CharField, TextInput, DateField, DateInput, Select, ModelMultipleChoiceField, \
    SelectMultiple, ModelChoiceField
from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    fullname = CharField(widget=TextInput(attrs={"class": "form-control"}))
    born_date = DateField(initial=datetime.date.today,
                          widget=DateInput(attrs={"class": "form-control", "type": "date"}))
    born_location = CharField(widget=TextInput(attrs={"class": "form-control"}))
    description = CharField(widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = "__all__"


class QuoteForm(ModelForm):
    tags = ModelMultipleChoiceField(widget=SelectMultiple(attrs={"class": "form-control"}), queryset=Tag.objects.all())
    # author = Select(attrs={"class": "form-control"}, choices=Author.objects.all())
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'),
                              widget=Select(attrs={"class": "form-select"}))
    quote = CharField(widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Quote
        fields = "__all__"

Python_web/modul10/hometask/mysite/app_my_site/views.py
import os

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .forms import AuthorForm, QuoteForm
from .models import Author, Quote, Tag


# Create your views here.
def main(request):
    return render(request, 'app_my_site/index.html', context={"title": "AUTHOR_QUOTE", "quotes": Quote.objects.all(), "tags": Tag.objects.all()})


@login_required
def upload_author(request):
    if request.method == "POST":
        author = AuthorForm(request.POST)
        if author.is_valid():
            author.save()
            return redirect(to='app_my_site:root')
        else:
            return render(request, 'app_my_site/upload_author.html', context={"title": "AUTHOR_QUOTE", "form": author})

    return render(request, 'app_my_site/upload_author.html', context={"title": "AUTHOR_QUOTE", "form": AuthorForm()})


def upload_quote(request):
    if request.method == "POST":
        quote = QuoteForm(request.POST)
        if quote.is_valid():
            quote.save()
            return redirect(to='app_my_site:root')
        else:
            return render(request, 'app_my_site/upload_quote.html', context={"title": "AUTHOR_QUOTE", "form": quote})

    return render(request, 'app_my_site/upload_quote.html', context={"title": "AUTHOR_QUOTE", "form": QuoteForm()})


def authors_descr(request, pk):
    author = get_object_or_404(Author, pk=pk)
    return render(request, 'app_my_site/authors_descr.html', context={"title": "AUTHOR_DESCRIPTION", "author": author})

Python_web/modul10/hometask/mysite/app_my_site/templates/app_my_site/authors_descr.html
{% extends "app_my_site/base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <br>Sometext here
                <div class="card">
                    <div class="card-body">
                      <h1 class="card-title">{{ author.fullname }}</h1>
                      <hr>
                      <h5 class="card-subtitle mb-2 text-muted">Born: {{ author.born_date}} {{ author.born_location}}</h5>
                      <hr>
                      <p class="card-text"><h5>Biography:</h5> {{ author.description}} </p>
                    </div>
                  </div>
            </div>
        </div>
    </div>

    

{% endblock content %}

Python_web/modul10/hometask/mysite/app_my_site/templates/app_my_site/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body>
<div class="container">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href="/">Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app_my_site:upload_author' %}">Upload Author</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app_my_site:upload_quote' %}">Upload Quote</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">LogOut</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">SignIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">SignUp</a>
          </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
</div>
</body>
</html>

Python_web/modul10/hometask/mysite/app_my_site/templates/app_my_site/index.html
{% extends "app_my_site/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10">
            {% for quote in quotes %}
            <blockquote class="blockquote pb-2">
                <p>{{quote.quote}}</p>
            </blockquote>
            <div class="blockquote mb-0">
                <h5>by <cite><a href="{% url 'app_my_site:authors_descr' quote.author.id %}">
                    {{quote.author.fullname}}</a>
                </cite></h5>
            </div>

            <h5>Tags:
                {% for tag in tags %}
                    <a type="submit" class="btn btn-primary btn-sm" name="tag_name" href="?tag_name={{tag}}">{{tag}}</a>
                {% endfor%}
            </h5>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

Python_web/modul10/hometask/mysite/app_my_site/templates/app_my_site/upload_author.html
{% extends "app_my_site/base.html" %}

{% block content %}
    <h1>Post a new article</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Post">
        <input type="hidden" name="next" value="{{ next }}">
    </form>
    {% if form.errors %}
    <ul class="user-msg error">
    {% for field in form %}
        {% for error in field.errors %}
            <li>
              {% if field != '__all__' %}
                <strong>{{ field.label }}:</strong>
              {% endif %}
              {{ error }}
            </li>
        {% endfor %}
    {% endfor %}
    </ul>
{% endif %}
{% endblock %}

Python_web/modul10/hometask/mysite/app_my_site/templates/app_my_site/upload_quote.html
{% extends "app_my_site/base.html" %}

{% block content %}
    <h1>Post new quote</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Post">
    </form>
    {% if form.errors %}
        <p>The form has the following errors:</p>
        <ul>
        {% for field in form %}
            {% for error in field.errors %}
                <li>{{ error|escape }}</li>
            {% endfor %}
        {% endfor %}
        </ul>
    {% endif %}
{% endblock %}